### ISSUE TITLE
Kitten u will be always be remembered uwu!

### ISSUE THREAD

**Issue by jokbon** [Titaniumtown/dotfiles#1]
:3

**Comment by jokbon** [comment]
![image](https://github.com/Titaniumtown/dotfiles/assets/29400409/9d6c23f7-f07a-4626-bdaa-e86704c1083f)

**Comment by Shelly333-2** [comment]
hello

**Comment by jokbon** [comment]
hello

**Comment by jokbon** [comment]
May yatopia factions long live!

**Comment by Titaniumtown** [comment]
wtf is yatopia factions
